### ISSUE TITLE
IMA sdk doesn't compile on MacBook Pro with M1 chip

### ISSUE THREAD

**Issue by madmet** [googleads/googleads-ima-ios#55] opened 2021-10-20 19:25 UTC
After adding pod reference to my podfile as following
`pod 'GoogleAds-IMA-iOS-SDK'`
and launching a `pod install` command, my app doesn't compile anymore on my MacBook Pro M1 using any iOS Simulator target facing the following compile time error:
```
Could not find module 'AnyModuleName' for target 'x86_64-apple-ios-simulator'; found: arm64, arm64-apple-ios-simulator, at: /Users/.../.../Debug-iphonesimulator/AnyModuleName.swiftmodule
```
Same project with the same podfile works without any problems on an Intel MacBook Pro (2,6 GHz 6-Core Intel Core i7).

**Comment by kemalenver** [comment] 2021-11-11 01:02
They haven't updated this to build an .xcframework yet. A lot of the google sdks don't.  @google-admin can you give an ETA on when you intend to support this?  While you're at it could you also support SPM? This is literally a 1-2 day job.

**Comment by Ghararym** [comment] 2022-02-18 09:35
The same issue here. @google-admin can you give us an ETA when you plan to support M1 and when will it support SPM?

**Comment by dominictobias** [comment] 2024-06-13 08:56
Is this fixed now? it what version

**Comment by NVentimiglia** [comment] 2024-06-26 19:56
@madmet I was unable to replicate this issue. Here is what I did.

- ran `pod install` on `Swift/BasicExample`
- Opened the workspace
- Ran the project

Please let me know if you have alternative steps.

**Comment by gschoppe** [comment] 2024-06-26 20:43
The IMA SDK for iOS has been packaged as an SDK since version [v3.16.3](https://developers.google.com/interactive-media-ads/docs/sdks/ios/client-side/history). Without confirmed reproducibility on a recent version I'm closing this as resolved for now

**Closed by gschoppe** 2024-06-26 20:43 UTC
